version: '3'
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  gammu-smsd:
    build:
      context: .
      dockerfile: Dockerfile
    image: colachen/gammu-smsd
    container_name: gammu-smsd
    restart: always
    privileged: true
    volumes:
      - "/dev/ec20:/dev/ec20"
      - "$PWD/supervisord.conf:/etc/supervisord.conf"
      - "$PWD/gammu-smsdrc:/etc/gammu-smsdrc"
      - "$PWD/python:/opt/python"
      - "/var/spool/gammu/:/var/spool/gammu/"
    environment:
      - "TZ=Asia/Hongkong"
      - "TELEGRAM_BOT_TOKEN=123"
      - "TELEGRAM_CHAT_ID=-123124141"
      - "CHANIFY_TOKEN=321"
      - "WEBHOOK_HOST=https://example.com:8443"
    ports:
      - "5000:5000"
    depends_on:
      - rabbitmq